<a href="https://colab.research.google.com/github/KaikyDegasperi/Tensores/blob/main/Opera%C3%A7%C3%B5esComTensores.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Operações

Agora que sabemos como construir tensores e como ler e escrever em seus elementos, podemos começar a manipulá-los com várias operações matemáticas. Entre as mais úteis estão as operações elementares. Estas aplicam uma operação escalar padrão a cada elemento de um tensor. Para funções que recebem dois tensores como entradas, as operações elementares aplicam algum operador binário padrão a cada par de elementos correspondentes. Podemos criar uma função elementar a partir de qualquer função que mapeie de um escalar para um escalar.

Na notação matemática, denotamos tais operadores escalares unários (que recebem uma entrada) pela assinatura $ f : \mathbb{R} \rightarrow \mathbb{R}$ . Isso significa apenas que a função mapeia de qualquer número real para algum outro número real. A maioria dos operadores padrão, incluindo operadores unários como $e^x $, podem ser aplicados elementarmente.


In [5]:
import torch

x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

Além das operações elementares, também podemos realizar operações algébricas lineares, como produtos internos e multiplicações de matrizes.

Também podemos concatenar vários tensores, empilhando-os um após o outro para formar um tensor maior. Apenas precisamos fornecer uma lista de tensores e informar ao sistema ao longo de qual eixo concatenar. O exemplo abaixo mostra o que acontece quando concatenamos duas matrizes ao longo das linhas (eixo 0) em vez de colunas (eixo 1). Podemos ver que o comprimento do eixo-0 da primeira saída (6) é a soma dos comprimentos do eixo-0 dos dois tensores de entrada (3 + 3); enquanto o comprimento do eixo-1 da segunda saída (8) é a soma dos comprimentos do eixo-1 dos dois tensores de entrada (4 + 4).


In [6]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

 Podemos contruir operações lógicas declarações lógicas. Tome X == Y como exemplo. Para cada posição i, j, se X[i, j] e Y[i, j] forem iguais, então a entrada correspondente no resultado recebe o valor 1, caso contrário, recebe o valor 0.



In [7]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

Somar todos os elementos no tensor resulta em um tensor com apenas um elemento.


In [9]:
X.sum()

tensor(66.)

##Broadcasting

Até agora, você sabe como realizar operações binárias elementares em dois tensores com o mesmo formato. Sob certas condições, mesmo quando os formatos diferem, ainda podemos realizar operações binárias elementares invocando o mecanismo de broadcasting. O broadcasting funciona de acordo com o seguinte procedimento em duas etapas: (i) expandir um ou ambos os arrays copiando elementos ao longo dos eixos com comprimento 1, para que após essa transformação, os dois tensores tenham o mesmo formato; (ii) realizar uma operação elementar nos arrays resultantes.


In [10]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

Como as matrizes a e b são de dimensões 3 × 1 e 1 × 2, respectivamente, seus formatos não se correspondem. O broadcasting produz uma matriz maior de dimensões 3 × 2 replicando a matriz a ao longo das colunas e a matriz b ao longo das linhas antes de adicioná-las elemento a elemento.


In [11]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])